language: go

go:
  - 1.9

go_import_path: github.com/zaquestion/lab

# use containers which run faster and have cache
sudo: false

script:
  - go test ./...

deploy:
  provider: script
  script: curl -sL https://git.io/goreleaser | bash
  on:
    branch: master
    tags: true

notifications:
  email: false
